export const ADMIN_PARAMS_REQUEST = 'ADMIN_PARAMS_REQUEST'
export const ADMIN_PARAMS_SUCCESS = 'ADMIN_PARAMS_SUCCESS'
export const ADMIN_PARAMS_FAIL = 'ADMIN_PARAMS_FAIL'

export const ADMIN_PARAMS_UPDATE_REQUEST = 'ADMIN_PARAMS_UPDATE_REQUEST'
export const ADMIN_PARAMS_UPDATE_SUCCESS = 'ADMIN_PARAMS_UPDATE_SUCCESS'
export const ADMIN_PARAMS_UPDATE_FAIL = 'ADMIN_PARAMS_UPDATE_FAIL'
