export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_DETAIL_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS'
export const ORDER_DETAIL_FAIL = 'ORDER_DETAIL_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_LIST_USER_REQUEST = 'ORDER_LIST_USER_REQUEST'
export const ORDER_LIST_USER_SUCCESS = 'ORDER_LIST_USER_SUCCESS'
export const ORDER_LIST_USER_FAIL = 'ORDER_LIST_USER_FAIL'
export const ORDER_LIST_USER_RESET = 'ORDER_LIST_USER_RESET'

export const ORDER_LIST_ADMIN_REQUEST = 'ORDER_LIST_ADMIN_REQUEST'
export const ORDER_LIST_ADMIN_SUCCESS = 'ORDER_LIST_ADMIN_SUCCESS'
export const ORDER_LIST_ADMIN_FAIL = 'ORDER_LIST_ADMIN_FAIL'
export const ORDER_LIST_ADMIN_RESET = 'ORDER_LIST_ADMIN_RESET'

export const ORDER_LIST_ADMIN_ALL_REQUEST = 'ORDER_LIST_ADMIN_ALL_REQUEST'
export const ORDER_LIST_ADMIN_ALL_SUCCESS = 'ORDER_LIST_ADMIN_ALL_SUCCESS'
export const ORDER_LIST_ADMIN_ALL_FAIL = 'ORDER_LIST_ADMIN_ALL_FAIL'
export const ORDER_LIST_ADMIN_ALL_RESET = 'ORDER_LIST_ADMIN_ALL_RESET'

export const ORDER_DELIEVERED_REQUEST = 'ORDER_DELIEVERED_REQUEST'
export const ORDER_DELIEVERED_SUCCESS = 'ORDER_DELIEVERED_SUCCESS'
export const ORDER_DELIEVERED_FAIL = 'ORDER_DELIEVERED_FAIL'
export const ORDER_DELIEVERED_RESET = 'ORDER_DELIEVERED_RESET'
